# Import this file using
#
# . ENV.sh

CEP_HOST=localhost
CEP_PORT=8089

CB_HOST=localhost
CB_PORT=1026

FED_CB_HOST=localhost
FED_CB_PORT=10026

E2I_HOST=localhost
E2I_PORT=5000

CYGNUS_HOST=localhost
CIGNUS_PORT=1028

IDAS_HOST=A.B.C.D

LOCS_HOST=localhost

export CEP_HOST CEP_PORT CB_HOST CB_PORT FED_CB_HOST FED_CB_PORT E2I_HOST E2I_PORT CYGNUS_HOST CYGNUS_PORT IDAS_HOST LOCS_HOST
